### ISSUE TITLE
ImportError: No module named 'models'

### ISSUE THREAD

**Issue by tubelius** [wordnik/wordnik-python#27]
[rubiksmomo@nakedman /]$ python ~/nakedman.py
Traceback (most recent call last):
  File "/home/rubiksmomo/nakedman.py", line 13, in <module>
    from wordnik import *
  File "/usr/lib/python3.5/site-packages/wordnik/WordListApi.py", line 23, in <module>
    from models import *
ImportError: No module named 'models'
[rubiksmomo@nakedman /]$

**Comment by asher2k4** [comment]
Try `import wordnik` instead of `from wordnik import *`. Unfortunately, "swagger" was no longer defined, and I haven't been able to find a fix.
